version: '3'

services:

  nginx:
    build: nginx/
    ports:
      - "8080:80"
    restart: always
    volumes:
      - ~/www/:/var/www/

  php7.1:
    build: ./php/7.1
    volumes:
      - ~/www/:/var/www/
  
  db1:
    container_name: db1
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3320:3306"    

  # NETWORK 
networks:
  default:
    external:
       name: test_bridge

